### ISSUE TITLE
.dmg installers are broken

### ISSUE THREAD

**Issue by IdlePhysicist** [Conky-for-macOS/Manage-Conky#26]
See screenshot below, unable to install using .dmg files.

![Screenshot 2019-07-24 at 09 00 47](https://user-images.githubusercontent.com/20644761/61804760-b8c2ab80-adf1-11e9-8e27-5d2baf65b638.png)

Mid-2015 MacBook Pro 15"
Running Mojave 10.14.5

**Comment by npyl** [comment]
Hi!
Thanks for reporting.
Please use one of the attached `.zip` files.
Releasing a `.dmg` will require some more time because apple enforces strict security rules.

I have also attached v0.9.9 (a version I have been baking locally for quite a while now, which contains bug fixes, improvements and more features.  It is *almost* ready for a release but [some](https://github.com/Conky-for-macOS/Manage-Conky/issues/24) things need to be taken care of first.) If you are interested give it a go; it will help me a lot to have testing feedback.

Hope the zips work for you.
~Nick.

[Manage Conky_0_9_3.zip](https://github.com/Conky-for-macOS/Manage-Conky/files/3428566/Manage.Conky_0_9_3.zip)
[Manage Conky_0_9_9.zip](https://github.com/Conky-for-macOS/Manage-Conky/files/3428567/Manage.Conky_0_9_9.zip)
